### ISSUE TITLE
License on AES implementation does not match upstream?

### ISSUE THREAD

**Issue by buzztiaan** [things4u/LoRa-LMIC-1.51#6]
https://github.com/Ideetron/RFM95W_Nexus/blob/master/LoRaWAN_V31/AES-128_V10.cpp says LGPL

but the same file in this repo says GPLv3

**Comment by platenspeler** [comment]
Hi buzztiaan,

I will update shortly. I did check with them before, as their code was missing license info on most places. Apparently me or them made a mistake. Will update.

thanks,

Maarten

**Comment by platenspeler** [comment]
Repaired in version 1.2.
