### ISSUE TITLE
Add "category=Communication" to library.properties to silence warning

### ISSUE THREAD

**Issue by kiwi64ajs** [things4u/LoRa-LMIC-1.51#7]
Hi,

Currently when you do a build, the Arduino IDE outputs a warning:

```
 WARNING: Category '' in library IBM LMIC framework v1.51 for Arduino is not valid. Setting to 'Uncategorized'
```

This can be fixed by adding the following line to the library.properties file:

```
 category=Communication
```

Regards

Alex Shepherd

**Comment by platenspeler** [comment]
Alex,

Thanks, I have updated the file. Hope it's working now.

Maarten
